// Generated by CoffeeScript 1.10.0
(function() {
  var construct, dictionary, objects;

  objects = {
    lightObject: {
      self: 'lightObject',
      name: 'light',
      properties: {
        'on': false,
        'brightness': 20,
        'timer': 50
      }
    }
  };

  dictionary = {
    verbs: [
      {
        phrase: "turn on",
        "function": "Modify.set",
        property: 'on',
        value: true
      }, {
        phrase: /set\s.*\sto/,
        "function": "Modify.set",
        value: null
      }
    ]
  };

  construct = function(dictionary, objects) {
    var key, value;
    dictionary.nouns = [];
    for (key in objects) {
      value = objects[key];
      dictionary.nouns.push({
        name: value.name,
        object: value
      });
    }
    return dictionary;
  };

  module.exports = {
    dictionary: construct(dictionary, objects),
    objects: objects
  };

}).call(this);
