// Generated by CoffeeScript 1.10.0
(function() {
  ({

    /* Generated by PseudoScript 0.1 */
    lightObject: {
      self: lightObject,
      name: light,
      properties: {
        on: false,
        brightness: 20,
        timer: 50
      }
    }
  });

  Modify.set(lightObject, true, true);

  Modify.set(lightObject, brightness, 45);

  Modify.set(lightObject, timer, 60);

  Modify.set(lightObject, true, true);

  Modify.set(lightObject, brightness, 45);

  Modify.set(lightObject, timer, 60);

}).call(this);
