
### Generated by PseudoScript 0.1 ###

lightObject:
  self: lightObject
  name: light
  properties:
    on: false
    brightness: 20
    timer: 50

# turn on light, set brightness to 45 and set timer to 60
Modify.set lightObject, on, true
Modify.set lightObject, brightness, 45
Modify.set lightObject, timer, 60

# turn on the light, set the brightness to 45 and set the timer to 60
Modify.set lightObject, on, true
Modify.set lightObject, brightness, 45
Modify.set lightObject, timer, 60
