// Generated by CoffeeScript 1.10.0
(function() {
  var begränsa, fisk, i, len, sjön, temperaturen, väder;

  sjön = [
    {
      art: 'gös',
      vikt: 1.3,
      insjöfisk: true,
      rutten: true
    }, {
      art: 'aborre',
      vikt: 0.8,
      insjöfisk: true,
      rutten: false
    }, {
      art: 'gädda',
      vikt: 3.2,
      insjöfisk: false,
      rutten: false
    }
  ];

  for (i = 0, len = sjön.length; i < len; i++) {
    fisk = sjön[i];
    console.log('');
    console.log(fisk.art);
    console.log(fisk.vikt);
    if (fisk.vikt > 1) {
      console.log("Stor fisk");
    } else {
      console.log("Liten fisk");
    }
    if (fisk.rutten) {
      console.log("Släng den!");
    } else {
      console.log("Spisa med behag!");
    }
  }

  begränsa = function(vikt, max) {
    if (vikt > max) {
      return 3;
    } else {
      return vikt;
    }
  };

  fisk = {
    art: 'torsk',
    vikt: 4
  };

  console.log('');

  console.log(begränsa(fisk.vikt, 3));

  console.log(fisk.vikt * 2 + 3);

  temperaturen = 24;

  väder = {
    fint: true,
    varmt: temperaturen > 20 ? true : false
  };

  console.log("Väderrapport: ");

  if (väder.fint && väder.varmt) {
    console.log("Ut and njut in solen!");
  } else {
    console.log("Nog bäst att stanna inne idag.");
  }


  /*
  kastade = 'Kjell'
  console.log "vem var det som kasta?"
  console.log  kastade
   */

}).call(this);
